your-tools/tbump

- tbump/git_bumper.py
As per the [Git Documentation](https://git-scm.com/docs/git-tag):
>Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels. For this reason, some git commands for naming objects (like git describe) will ignore lightweight tags by default.
Note that I just happily changed the behavior, but you might want to introduce an option instead.
> Create tag objects instead of lightweight tags

- requirements.lock
- tbump/main.py
> Catch git errors when run with --dry-run instead of aborting

- tbump/init.py
`--init` creates a tbum.toml templates that contains invalid quoting when uncommenting the github url section.
```shell
$ tbump init 0.2.3
:: Generating tbump config file
=> ✓ Generated tbump.toml
$ tbump --dry-run 0.2.4
Error: Invalid config: Unexpected character: 'h' at line 2 col 13
```
> Fix invalid syntax in template

- Changelog.rst
- tbump/git_bumper.py
- tbump/hooks.py
- tbump/main.py
- tbump/test/test_git_bumper.py
- tbump/test/test_main.py
This is useful when using `tbump` with PKGBUILD files: the git backend
of aur.archlinux.org does not allow to push tags, but it's still useful
to have them locally.
> Allow to create the tag but not push it

- poetry.lock
- pyproject.toml
I would like to use tbump in a project where I already use tomlkit - in version `0.7`
The current dependency in tbump only allows versions `<0.6`. In a smoketest it seemed working with 0.7.0 just fine
> allow usage of newer tomlkit versions

- tbump/init.py
- tbump/main.py
Random stuff I found while playing around 
1. an unused variable
2. using `init --pyproject` does generate a wrong config as the `github_url` is not under the `[tool.tbump]` header
> Small improvements

- poetry.lock
- pyproject.toml
We need to bump minimum python version for black in order
to fix a problem with dataclasses when solving dependencies for
python 3.10
> pyproject: fix for Python 3.10

- tbump/config.py
- tbump/file_bumper.py
- tbump/test/project/tbump.toml
- tbump/test/project/version_info.py
- tbump/test/test_config.py
- tbump/test/test_main.py
allows a version_template to include fields without a match in the version regex without triggering BadSubstitution.
It's not possible to *omit* fields, which would require a different version template, but they can be empty strings, 0, etc.
This seemed to fit best into how things work for other options, but happy to change names of things, or just close if you don't like how this looks. In particular, I don't know if `field` is the right name for it, but it is what came to mind.
closes #121
> add config for field defaults

- tbump/file_bumper.py
Also, rename 'match' variable (it became a keyword in Python 3.10)
> Fix a mypy error

- tbump/file_bumper.py
> Follow-up on the "default fields" feature

- poetry.lock
- pyproject.toml
attr uses calver, so specifying "^19" clearly does not
work as intended
Fix #123 
Although, to be honest I'm considering dropping the dependency on `attr` and use `dataclasses` from the stdlib instead, but that would mean bumping the minimum required version of Python to 3.7
> Bump attr and relax its version constraints

- README.rst
grep uses regex. `.` means "any character", so the check may pass even if the content of the file is wrong
Example:
`2021-11-18:  Release 0.1.0` passes `grep -q 0.1.1` but fails `grep -q -F 0.1.1`.
> Fix grep parameter

- pyproject.toml
According to the [dependency specification](https://python-poetry.org/docs/dependency-specification/)
`^1.2.3` means `>=1.2.3 <2.0.0`, but `^0.2.3` means `>=0.2.3 <0.3.0`.
Your current version of `cli-ui` is `0.15.2` which is out of the scope of `^0.10.3` (which actually means `>=0.10.3, <0.11.0`).
In order to submit your `tbump` package to conda-forge, I need to submit `cli-ui` to conda-forge as well. The CI complains on this issue.
By the way, to fix the dependency, you will need to bump a new version number of `tbump` to PyPI as well.
> Relax dependency requirement on cli-ui

- tbump/cli.py
- tbump/config.py
- tbump/executor.py
- tbump/file_bumper.py
- tbump/test/test_file_bumper.py
This change reduces the number of classes that directory know about `ConfigFile`. This is another small step towards #143. The end goal is to have these classes work off a `Config` like dataclass that is distinct from the config file format and is the result of merging the settings specified in the config file and any given command line arguments. The data structures being introduced might not survive the whole process. But I find it easier these seams in smalls steps that can be cleaned up afterward if necessary.
> Abtract away config file

- tbump/cli.py
- tbump/test/test_cli.py
Fixes:
```
operations.remove("push_tag")
ValueError: list.remove(x): x not in list
```
when specifying `--no-push` and `--no-tag-push`
> fix removing nonexistent element from list

- tbump/cli.py
- tbump/git_bumper.py
- tbump/test/conftest.py
- tbump/test/test_cli.py
- tbump/test/test_git_bumper.py
Add a command line option to specify the tag message instead of it always being based on the tag itself
(This is the same as https://github.com/your-tools/tbump/pull/152 but I can't edit the 'head' of an existing PR?)
> Add tag-message command line option

- tbump/file_bumper.py
I generated a tbump.toml file using `tbump init` and i did not edit the file.src configuration string and subsequently got this error 
which did not really helped because it took some time to figure out he the `...` was the file.src config string. So i changed the error message to  make that easy to understand
> add context to error

- .gitignore
- tbump.toml
- tbump/config.py
- tbump/git_bumper.py
fixes https://github.com/your-tools/tbump/issues/133
Same solution as the actual optional argument `atomic_push`.
`poetry run pytest` passes
No new tests were added.
>  tbump should be able to make signed tag #133 

- tbump/config.py
fixes #168
It works with relative path
```
(tbump-py3.12) ➜  tbump git:(main) ✗ tbump --config ./../tbump/tbump.toml 0.10.1 --only-patch
:: Bumping from 6.11.0 to 0.10.1
/home/slash/CODE/github.com/slashformotion/tbump
../tbump/tbump.toml
/home/slash/CODE/github.com/slashformotion/tbump/../tbump/tbump.toml
=> Would update current version in /home/slash/CODE/github.com/slashformotion/tbump/../tbump/tbump.toml
/home/slash/CODE/github.com/slashformotion/tbump
../tbump/tbump.toml
/home/slash/CODE/github.com/slashformotion/tbump/../tbump/tbump.toml
- /home/slash/CODE/github.com/slashformotion/tbump/../tbump/tbump.toml:6 current = "6.11.0"
+ /home/slash/CODE/github.com/slashformotion/tbump/../tbump/tbump.toml:6 current = "0.10.1"
=> Would patch these files
- pyproject.toml:6 version = "6.11.0" …
```
> fix: relative config path error fix

- .gitignore
- tbump.toml
- tbump/file_bumper.py
fixes https://github.com/your-tools/tbump/issues/112
Check if `old_string == new_string` for `ChangeRequest` before adding to the change requests.
With the following template:
```
[version]
current = "6.11.0"
regex = '''
(?P<major>\d+)
\.
(?P<minor>\d+)
\.
(?P<patch>\d+)
(\-
(?P<extra>.+)
)?
'''
...
[[file]]
src = "tbump/cli.py"
version_template = "{major}.{minor}.{patch}"
```
run the command `python -m tbump 6.11.0-1 --dry`
```
:: Bumping from 6.11.0 to 6.11.0-1
=> Would update current version in tbump.toml
- tbump.toml:6 current = "6.11.0"
+ tbump.toml:6 current = "6.11.0-1"
=> Would patch these files
- pyproject.toml:6 version = "6.11.0"
+ pyproject.toml:6 version = "6.11.0-1"
- tbump/cli.py:21 TBUMP_VERSION = "6.11.0"
+ tbump/cli.py:21 TBUMP_VERSION = "6.11.0"
=> Would run these hooks …
```
>  Output messages are sometimes misleading #112 
